import {json,requireUser,audit} from '../../_lib/auth.js';
import {paystack} from '../../_lib/paystack.js';
export async function onRequestGet({request,env}){try{const u=await requireUser(request,env);const r=await env.DB.prepare('SELECT id,bank_code,bank_name,account_number_masked,account_name,currency,verified,recipient_code,created_at FROM beneficiaries WHERE user_id=? ORDER BY created_at DESC').bind(u.id).all();return json({beneficiaries:r.results||[]})}catch(e){return e instanceof Response?e:json({error:'Unable to load beneficiaries.'},500)}}
export async function onRequestPost({request,env}){
 try{const u=await requireUser(request,env);const b=await request.json();const bankCode=String(b.bankCode||'').trim(),accountNumber=String(b.accountNumber||'').replace(/\D/g,'');if(!/^\d{10}$/.test(accountNumber)||!bankCode)return json({error:'Enter a valid 10-digit Nigerian account number and bank code.'},400);
 const resolved=await paystack(env,`/bank/resolve?account_number=${encodeURIComponent(accountNumber)}&bank_code=${encodeURIComponent(bankCode)}`);const name=resolved.data?.account_name||'';if(!name)return json({error:'The bank account could not be verified.'},422);
 const rec=await paystack(env,'/transferrecipient',{method:'POST',body:JSON.stringify({type:'nuban',name,account_number:accountNumber,bank_code:bankCode,currency:'NGN',description:`Aurevia beneficiary ${u.id}`})});
 const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO beneficiaries(id,user_id,recipient_code,bank_code,bank_name,account_number_masked,account_name,currency,verified) VALUES(?,?,?,?,?,?,?,?,1)').bind(id,u.id,rec.data.recipient_code,bankCode,String(b.bankName||''),`******${accountNumber.slice(-4)}`,name,'NGN').run();await audit(env,u.id,'beneficiary.created',{beneficiary:id,bankCode});return json({beneficiary:{id,recipient_code:rec.data.recipient_code,bank_code:bankCode,account_name:name,account_number_masked:`******${accountNumber.slice(-4)}`,verified:1}},201);
 }catch(e){return e instanceof Response?e:json({error:e.message==='PAYSTACK_NOT_CONFIGURED'?'Payments are not configured yet. Add PAYSTACK_SECRET_KEY in Cloudflare secrets.':(e.provider?.message||'Unable to verify bank account.')},502)}
}
